CU-57wkhp fix deb install issue by software manager on Ubuntu.

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -5,8 +5,14 @@ set -e
 . /usr/share/debconf/confmodule
 
 case "$1" in
-  upgrade|install)
-    db_get rcdiscover/rpfilter || true
+  configure)
+    db_get feedsd/agreement || true
+    if [ "$RET" != "true" ]; then
+      if [ "$RET" != "false" ]; then
+        echo "Failed to ensure feedsd agreement, error($RET)" >&2
+      fi
+      exit 1
+    fi
   ;;
 
   abort-upgrade|abort-remove|abort-deconfigure)
