CU-57wkhp fix deb install issue by software manager on Ubuntu.

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -5,11 +5,13 @@ set -e
 . /usr/share/debconf/confmodule
 
 case "$1" in
-  configure)
+  upgrade|install)
     db_get feedsd/agreement || true
-    if [ "$RET" != "true" ]; then
-      if [ "$RET" != "false" ]; then
-        echo "Failed to ensure feedsd agreement, error($RET)" >&2
+    AGREE=$RET 
+    db_purge
+    if [ "$AGREE" != "true" ]; then
+      if [ "$AGREE" != "false" ]; then
+        echo "Failed to ensure feedsd agreement, error($AGREE)" >&2
       fi
       exit 1
     fi
